AllCops:
    NewCops: enable
    TargetRubyVersion: 2.7

Gemspec/RequireMFA:
  AutoCorrect: false

Layout/ExtraSpacing:
  Exclude:
    - '*.gemspec'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'spec/kanakana_spec.rb'

Layout/SpaceAroundOperators:
  Exclude:
    - '*.gemspec'

Metrics:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false
